# Form implementation generated from reading ui file 'BMI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BMI(object):
    def setupUi(self, BMI):
        BMI.setObjectName("BMI")
        BMI.resize(494, 137)
        self.layoutWidget = QtWidgets.QWidget(parent=BMI)
        self.layoutWidget.setGeometry(QtCore.QRect(1, 1, 491, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_weight = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_weight.setObjectName("label_weight")
        self.horizontalLayout.addWidget(self.label_weight)
        self.lineEdit_weight = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_weight.setEnabled(True)
        self.lineEdit_weight.setObjectName("lineEdit_weight")
        self.horizontalLayout.addWidget(self.lineEdit_weight)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_height = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_height.setObjectName("label_height")
        self.horizontalLayout_2.addWidget(self.label_height)
        self.lineEdit_height = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit_height.setObjectName("lineEdit_height")
        self.horizontalLayout_2.addWidget(self.lineEdit_height)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.pushButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.label_suggest = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_suggest.setWordWrap(True)
        self.label_suggest.setObjectName("label_suggest")
        self.horizontalLayout_3.addWidget(self.label_suggest)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_result = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_result.setObjectName("label_result")
        self.verticalLayout_3.addWidget(self.label_result)

        self.retranslateUi(BMI)
        QtCore.QMetaObject.connectSlotsByName(BMI)

    def retranslateUi(self, BMI):
        _translate = QtCore.QCoreApplication.translate
        BMI.setWindowTitle(_translate("BMI", "人体BMI计算器"))
        self.label_weight.setText(_translate("BMI", "请输入你的体重(KG)："))
        self.label_height.setText(_translate("BMI", "请输入你的身高(cm)："))
        self.pushButton.setText(_translate("BMI", "计算BMI"))
        self.label_suggest.setText(_translate("BMI", "提示：1. 中国成人居民BMI衡量标准是小于等于18.1为偏瘦；18.5-23.9为正常；24-27.9为超重；大于等于28为肥胖。2. 最理想的BMI数值为22，理想体重 = 22 x 身高2 (米)，±10%波动"))
        self.label.setText(_translate("BMI", "您的计算结果："))
        self.label_result.setText(_translate("BMI", "BMI：27.18，属于超重 您的理想体重为：68KG"))
